name: Continuous Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    uses: myfin-tracker/application/.github/workflows/depolyment.yml@main
